#!/bin/sh
/usr/bin/touch /tmp/keylogger.log && /bin/chmod 600 /tmp/keylogger.log && /usr/local/bin/logkeys --start --output /tmp/keylogger.log --no-timestamps
/usr/bin/tail -f /tmp/keylogger.log | /usr/local/bin/ultimatewriter
